### ISSUE TITLE
Add ocropy/kraken support

### ISSUE THREAD

**Issue by wrznr** [OCR-D/ocrd-train#12]

**Comment by kba** [comment]
:+1: in general. Since the tesseract recipe is substantially more complex that using kraken's ketos or ocropy, I'm not sure whether it is a good idea to support all in the same Makefile.

Maybe put different training backends into subdirectories, each with their own Makefile and README.md.
We can still use the same conventions for names of image source directories etc.

**Comment by wrznr** [comment]
Superseded by https://github.com/Doreenruirui/okralact
