### ISSUE TITLE
ERROR: cannot verify github.com's certificate

### ISSUE THREAD

**Issue by cuonghust** [OCR-D/ocrd-train#78]
When I run : make training with sample test. After run few minute, it happens.

# https://www.gnu.org/software/coreutils/manual/html_node/Random-sources.html#Random-sources
find data/ground-truth -name '*.lstmf' | sort | \
  sort -R --random-source=<(openssl enc -aes-256-ctr -pass pass:"0" -nosalt </dev/zero 2>/dev/null) > "data/all-lstmf"
total=`cat data/all-lstmf | wc -l` \
   no=`echo "$total * 0.90 / 1" | bc`; \
   head -n "$no" data/all-lstmf > "data/list.train"
total=`cat data/all-lstmf | wc -l` \
   no=`echo "($total - $total * 0.90) / 1" | bc`; \
   tail -n "$no" data/all-lstmf > "data/list.eval"
wget -Odata/radical-stroke.txt 'https://github.com/tesseract-ocr/langdata_lstm/raw/master/radical-stroke.txt'
--2019-08-28 01:02:51--  https://github.com/tesseract-ocr/langdata_lstm/raw/master/radical-stroke.txt
Resolving github.com (github.com)... 15.164.81.167
Connecting to github.com (github.com)|15.164.81.167|:443... connected.
ERROR: cannot verify github.com's certificate, issued by ‘.......’: Unable to locally verify the issuer's authority.
To connect to github.com insecurely, use `--no-check-certificate'.
Makefile:176: recipe for target 'data/radical-stroke.txt' failed

Please help me resolve it. Thank you !

**Comment by stweil** [comment]
This might be caused by a [man-in-the-middle](https://en.wikipedia.org/wiki/Man-in-the-middle_attack), maybe your own IT department. Some IT departments think that it is a good idea to control what users are doing in the Internet. That information should be available in the `issued by`. Ask your IT department to fix this. Or do as suggested by the error message.
