### ISSUE TITLE
Failed to load any lstm-specific dictionaries for lang XXXX!!

### ISSUE THREAD

**Issue by Jitendradubey** [OCR-D/ocrd-train#79]
Hi,

We have used OCR-D for training the tesseract 4.0, We have trained tesseract 4.0 by using ocrd-train with error rate is 0.3,
But We are going to test with latest generated trained model, We got error.

Error : Failed to load any lstm-specific dictionaries for lang XXX!!

Thank in advance.

**Comment by wrznr** [comment]
Most likely a path problem. You either have to copy your model to a place where Tesseract looks for it or you have to tell Tesseract where to look for your new model. Pls. refer to the Tesseract manual.

**Comment by stweil** [comment]
@Jitendradubey, you did not get an error. You only got an informational message `Failed to load any lstm-specific dictionaries for lang XXX!!` from Tesseract. As you have created a new model, that is normal. Either ignore the message or add a dictionary to your model.

**Comment by kba** [comment]
> Failed to load any lstm-specific dictionaries for lang XXX!

Could this be marked as a warning instead of an error perhaps @stweil? Seems to be a common issue of confusion for trained models not packaged with any dictionaries (such as those produced by ocrd-train). Even @cneud stumbled over it this morning :)

**Comment by stweil** [comment]
It is not marked as an error (no "error" in the message text(, that's why I wrote "you did not get an error". And yes, it is confusing, like other messages of Tesseract, too.

When thinking in logging categories, it might even be less than a warning, maybe log level INFO.

Adding log levels to the Tesseract code and replacing the different methods used for logging today is one of many open tasks. That would also allow better integration of `libtesseract` into other software (like for example `tesserocr`).

**Comment by 24121987** [comment]
Sorry for late response.
thank you to all ..please mark as closed.
issue has been solved
